CREATE TABLE user_accounts (
    id UUID PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL,
    full_name VARCHAR(160) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_accounts_email UNIQUE (email),
    CONSTRAINT ck_user_accounts_role CHECK (role IN ('PATIENT', 'DOCTOR', 'ADMIN'))
);

CREATE TABLE patients (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES user_accounts(id),
    date_of_birth DATE NOT NULL,
    address VARCHAR(500) NOT NULL
);

CREATE TABLE doctors (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES user_accounts(id),
    license_number VARCHAR(100) NOT NULL UNIQUE,
    biography VARCHAR(2000) NOT NULL DEFAULT '',
    years_of_experience INTEGER NOT NULL DEFAULT 0,
    consultation_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_doctor_experience CHECK (years_of_experience >= 0),
    CONSTRAINT ck_doctor_fee CHECK (consultation_fee >= 0)
);

CREATE TABLE specializations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE doctor_specializations (
    doctor_id UUID NOT NULL REFERENCES doctors(id),
    specialization_id BIGINT NOT NULL REFERENCES specializations(id),
    PRIMARY KEY (doctor_id, specialization_id)
);

CREATE TABLE doctor_availability (
    id UUID PRIMARY KEY,
    doctor_id UUID NOT NULL REFERENCES doctors(id),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_availability_window CHECK (starts_at < ends_at)
);
CREATE INDEX ix_availability_doctor_time
    ON doctor_availability (doctor_id, starts_at, ends_at);

CREATE TABLE appointments (
    id UUID PRIMARY KEY,
    patient_id UUID NOT NULL REFERENCES patients(id),
    doctor_id UUID NOT NULL REFERENCES doctors(id),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_appointment_window CHECK (starts_at < ends_at),
    CONSTRAINT ck_appointment_status CHECK (
        status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')
    )
);
CREATE INDEX ix_appointments_doctor_time ON appointments (doctor_id, starts_at, ends_at);
CREATE INDEX ix_appointments_patient_time ON appointments (patient_id, starts_at DESC);

CREATE TABLE prescriptions (
    id UUID PRIMARY KEY,
    appointment_id UUID NOT NULL REFERENCES appointments(id),
    patient_id UUID NOT NULL REFERENCES patients(id),
    doctor_id UUID NOT NULL REFERENCES doctors(id),
    medication_name VARCHAR(200) NOT NULL,
    dosage VARCHAR(200) NOT NULL,
    frequency VARCHAR(200) NOT NULL,
    instructions VARCHAR(2000) NOT NULL DEFAULT '',
    valid_until DATE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_prescriptions_patient_issued ON prescriptions (patient_id, issued_at DESC);
CREATE INDEX ix_prescriptions_doctor_issued ON prescriptions (doctor_id, issued_at DESC);

-- Medical records are stored separately from API response DTOs. No endpoint returns
-- this table; future access must be explicitly scoped to the patient/care team.
CREATE TABLE medical_records (
    id UUID PRIMARY KEY,
    patient_id UUID NOT NULL REFERENCES patients(id),
    doctor_id UUID NOT NULL REFERENCES doctors(id),
    appointment_id UUID REFERENCES appointments(id),
    title VARCHAR(200) NOT NULL,
    details TEXT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_medical_records_patient_recorded ON medical_records (patient_id, recorded_at DESC);

INSERT INTO specializations (name) VALUES
    ('Cardiology'),
    ('Dermatology'),
    ('Family Medicine'),
    ('Neurology'),
    ('Pediatrics'),
    ('Psychiatry')
ON CONFLICT (name) DO NOTHING;