/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ApiAdminSetupGuideRouteImport } from './routes/api/admin-setup-guide'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSetupGuideRoute = ApiAdminSetupGuideRouteImport.update({
  id: '/api/admin-setup-guide',
  path: '/api/admin-setup-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-setup': typeof AdminSetupRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/api/admin-setup-guide': typeof ApiAdminSetupGuideRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-setup': typeof AdminSetupRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/api/admin-setup-guide': typeof ApiAdminSetupGuideRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/doctors': typeof DoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-setup': typeof AdminSetupRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/records': typeof RecordsRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/api/admin-setup-guide': typeof ApiAdminSetupGuideRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-setup'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/prescriptions'
    | '/records'
    | '/register'
    | '/services'
    | '/api/admin-setup-guide'
    | '/doctors/$id'
    | '/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-setup'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/prescriptions'
    | '/records'
    | '/register'
    | '/services'
    | '/api/admin-setup-guide'
    | '/doctors/$id'
    | '/doctors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-setup'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/prescriptions'
    | '/records'
    | '/register'
    | '/services'
    | '/api/admin-setup-guide'
    | '/doctors/$id'
    | '/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DoctorRoute: typeof DoctorRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  RecordsRoute: typeof RecordsRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  ApiAdminSetupGuideRoute: typeof ApiAdminSetupGuideRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-setup-guide': {
      id: '/api/admin-setup-guide'
      path: '/api/admin-setup-guide'
      fullPath: '/api/admin-setup-guide'
      preLoaderRoute: typeof ApiAdminSetupGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminSetupRoute: AdminSetupRoute,
  AppointmentsRoute: AppointmentsRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DoctorRoute: DoctorRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  RecordsRoute: RecordsRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  ApiAdminSetupGuideRoute: ApiAdminSetupGuideRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
